### ISSUE TITLE
I just tried Netlify Identity

### ISSUE THREAD

**Issue by yuminatwca** [netlify/ask-netlify#12]
## About me

- **My name:** Yumin Gui ( github.com/yuminatwca,  github.com/medmin)
- **I've used Netlify:** lots 

## My question in a little more detail

I have no question to ask.

## Anything other comments for Netlify

I just want to say that the Netlify Identity Widget is so freaking awesome and it's into details and it's one hundred million times easiser to use than Auth0.

Thumb Up!!!

**Comment by philhawksworth** [comment]
Thanks a lot @yuminatwca! The team who worked on that will be delighted to hear that it's working out for you.

**Comment by sw-yx** [comment]
Yay!!!!!

**Comment by philhawksworth** [comment]
Answered in Ep2 - coming soon:
https://ask.netlify.com/episode/02/

**Comment by sw-yx** [comment]
broken link

**Comment by philhawksworth** [comment]
Yeah, the episode has yet to be published.
Added a 404 for the enthusiastic on github :)
