### ISSUE TITLE
Deploy never ends

### ISSUE THREAD

**Issue by PeterKDunn** [netlify/ask-netlify#13]
## About me

Hi, I'm Pete and new at using Netlify.

I have deployed a couple of times as trials, and all went well... but now there is a deploy that never ends.

The deploy log shows that spinning thing... and has done so for days.

I cannot see a way to interrupt it, or stop it.

Any advice? Is there another approach?

Thanks for help.

P.

**Comment by philhawksworth** [comment]
Builds should timeout after 30 minutes if they don't succeed or fail after 30 minutes. If that is not happening, then this sounds like there is a bug or an issue somewhere.

If you are still seeing this, I'd recommend contacting our support team, @PeterKDunn. They can investigate and help out. https://netlify.com/support

Meanwhile, to help identify processes which might cause builds to hang or run long, we recently released some tooling to help make that more visible:

https://www.netlify.com/blog/2018/11/28/fearless-deploys-for-your-lingering-processes/
