### ISSUE TITLE
When can we get IPv6 on Netlify?

### ISSUE THREAD

**Issue by philhawksworth** [netlify/ask-netlify#2]
## About me

- **My name:** Phil Hawksworth
- **I've used Netlify:** lots

## My question in a little more detail

A lot of people have been asking for IPv6 support on the Netlify CDN. That seems to be taking a long time. Why is that and when might we expect it?

**Comment by DirtyF** [comment]
See https://www.netlify.com/blog/2018/11/26/announcing-ipv6-support-on-the-netlify-application-delivery-network/

**Comment by JOduMonT** [comment]
sorry to act as a grave digger but
@DirtyF what is the equivalent of IPv4 104.198.14.52
in IPv6 if I host my DNS somewhere else ?
