### ISSUE TITLE
How to filter netlify access in google analytics

### ISSUE THREAD

**Issue by ChrisLasar** [netlify/ask-netlify#25]
## About me

- **My name:** Christian Lasarczyk
- **I've used Netlify:** a little

## My question in a little more detail

After every rebuild I see a netlify access in google analytics. Can you suggest a filter to remove access of the infrastructure from analytics?

## Additional comments for Netlify

I really feel your passion behind this wonderful service.

**Comment by philhawksworth** [comment]
Answered in Ep2 - coming soon:
https://ask.netlify.com/episode/02/

**Comment by motiejunas** [comment]
> Answered in Ep2 - coming soon:
> https://ask.netlify.com/episode/02/

Could you prove the answer right here? Or at least provide the time range in video when you are talking about it. Not going to watch full episode just for it. Thanks.

**Comment by skix123** [comment]
Hi! Any news about excluding Netlify from GA?

**Comment by ermakovich** [comment]
@skix123 The easiest way is to go to GA admin settings and to create filter to include only traffic to your public hostname. I analyzed access logs and realized that in most cases netlify uses hostname like `master--${property}.netlify.com`. This method will also help to filter out all previous traffic registered in GA.

Here is how filter looks like in my case:

<img width="478" alt="Screen Shot 2019-08-28 at 12 22 24 PM" src="https://user-images.githubusercontent.com/1196011/63843925-e4582900-c98f-11e9-91b6-464eedc0473d.png">
