### ISSUE TITLE
How do you add Netlify deploy preview for a GitHub repo?

### ISSUE THREAD

**Issue by dance2die** [netlify/ask-netlify#26]
## About me

- **My name:** Sung Kim
- **I've used Netlify:** Frequently for demo/side projects.

## My question in a little more detail

I've seen sites on GitHub Pull Requests (PR) with following bots showing Netlify previews.
(_below is an [example PR](https://github.com/reactjs/reactjs.org/pull/1514) on Reactjs.org repo_)

![screenshot from 2019-01-04 23-41-44](https://user-images.githubusercontent.com/8465237/50720388-6f3f8880-107a-11e9-8717-dfd2bedd7c07.png)

Here is another [example PR](https://github.com/reduxjs/redux/pull/3317)  for Redux documentation.

![screenshot from 2019-01-04 23-47-52](https://user-images.githubusercontent.com/8465237/50720425-3358f300-107b-11e9-9566-582bf5918941.png)

How can one set up Netlify previews on a GitHub repo?

_I think I've set it up for few long time ago but can't seem to figure out any more..._ 🤔😅

## Additional comments for Netlify

Thank you for making site deployment easy 😀.
You guys are awesome 👍

**Comment by miguelmota** [comment]
@philhawksworth How do you set this up? wondering the same thing

**Comment by miguelmota** [comment]
Found answer here https://docs.netlify.com/site-deploys/notifications/#github-commit-statuses
