### ISSUE TITLE
How do I control cache duration on the CDN?

### ISSUE THREAD

**Issue by philhawksworth** [netlify/ask-netlify#3]
## About me

- **My name:** Phil Hawksworth
- **I've used Netlify:** lots

## My question in a little more detail

Do you support the "s-max-age" headers to control how long a file is cached in the CDN, say passing thru a proxy set in netlify.toml config?

**Comment by philhawksworth** [comment]
Worth mentioning:

https://www.netlify.com/blog/2018/11/26/announcing-ipv6-support-on-the-netlify-application-delivery-network/

**Comment by futuregerald** [comment]
A great blog post on how Netlify handles caching for you:

https://www.netlify.com/blog/2017/02/23/better-living-through-caching/
