### ISSUE TITLE
Netlify Analytics

### ISSUE THREAD

**Issue by manniL** [netlify/ask-netlify#32]
## About me

- **My name:** -> Alex 😋 
- **I've used Netlify:** excessively

## My question in a little more detail

I'd love to see some kind of Analytics finding it's way to Netlify. Client-side tracking á la Google Analytics is becoming less and less effective every day because of tracking and ad blockers. Any chance we'll see something like that? :relaxed: 

## PS

Netlify Socks as merch would be awesome! I'd love to wear some :heart:

**Comment by gubikmic** [comment]
I have the same question. Is there any kind of page view statistics planned?

**Comment by manniL** [comment]
Answering my own Q: 
https://www.netlify.com/blog/2019/07/10/netlify-analytics---accurate-insights-without-performance-impacts/
