### ISSUE TITLE
why netlify DNS?

### ISSUE THREAD

**Issue by sw-yx** [netlify/ask-netlify#33]
## About me

- **My name:** swyx
- **I've used Netlify:** lots

## My question in a little more detail

hey what is the benefit of using  Netlify DNS?

for example for a domain i bought on google domains
why would i use netlify DNS over google’s DNS

google's DNS has email forwarding features i like, and i lost it when i transferred to netlify DNS. is there some way to keep it?

**Comment by sw-yx** [comment]
gerald says:

You can use an alias record on the bare domain, Google domains doesn't support that

- Which gives you the benefits of came on the bare domain
- We will also be able to get you a wildcard certificate if you use Netlify dns
- And we will also be able to auto provision branch subdomains

**Comment by talves** [comment]
Yeah, but can we still MX records back to Google Mail ❔ or is that an issue with google domain also ❔

**Comment by talves** [comment]
@sw-yx sorry for the noise. Mostly trying to add to the question you were feeding to add value if possible.

**Comment by edcous** [comment]
@sw-yx Actually, you can keep the email forwarding, you have to add the email forwarding on google domains, and then export the resource records as a bind, open it, and find the place where it shows the mx records, you can now put that in netlify and it should work!

**Comment by sw-yx** [comment]
woosh. ok not something i do often haha. i will refer back to this when the time comes. thank you!

**Comment by edcous** [comment]
@sw-yx Sure, but just so you know, Google domains phone support can't help you with your domain records, plus I don't think you can use dnssec, so I don't know if Netlify dns is actually worth it, instead of doing cname records.
P.S. the .bind will also have all of your dns records so you can just add them in (besides the ones from Netlify, as that's automatically added)

**Comment by rootkea** [comment]
> plus I don't think you can use dnssec

With whom? Google Domains or Netlify DNS?

**Comment by edcous** [comment]
Netlify DNS

**Comment by rootkea** [comment]
I just opened a feature request at Netlify forums (frequented by Netlify staff) for DNSSEC support. Please share your views/support there: https://community.netlify.com/t/feature-requests-what-do-you-already-love-what-could-be-better/256/26
