### ISSUE TITLE
what happens if my site or functions get ddos'ed by a bad actor?

### ISSUE THREAD

**Issue by sw-yx** [netlify/ask-netlify#34]
## About me

- **My name:** swyx
- **I've used Netlify:** lots

## My question in a little more detail

what it says on the tin. is there any protection for me (financially or otherwise) if someone randomly decides to send a bunch of junk requests at my functions or sites and how does Netlify know what's valid or not valid?

**Comment by Sceat** [comment]
@philhawksworth why the close ?

**Comment by j-f1** [comment]
It looks like they planned to put it into episode 3 of the podcast, but [that was never released](https://ask.netlify.com).
