### ISSUE TITLE
What's in the Netlify pipes?

### ISSUE THREAD

**Issue by DirtyF** [netlify/ask-netlify#4]
## About me

- **My name:** Frank Taillandier
- **I've used Netlify:** lots 

## My questions

@biilmann demoed a nice FaunaDB integration at the first JAMstack conference.
Are there any other integrations planned at Netlify?

@mcat demoed a JAMstack job board developed within the GraphQL Headless CMS Takeshape during the last JAMstack NYC meetup, we saw that it has a nice Netlify integration, you can create your Netlify website within Takeshape and deploy it. Are you aware of other products that have a similar Netlify integration?

Any plan for a GraqhQL layer for the [Netlify API](https://open-api.netlify.com)? 

Thanks

**Comment by philhawksworth** [comment]
Related more general question noted in TND slack:
"Is there a Netlify Roadmap?"

**Comment by DirtyF** [comment]
stackbit.com is a new service that allows you to configure a static website (theme, SSG, CMS, deployment) in a few clicks that will deploy to Netlify.
