### ISSUE TITLE
Is Free plan reliable enough for a client project and does it use CDN? Why isn't there a cheaper paid plan for very small projects?

### ISSUE THREAD

**Issue by marinoguerieri** [netlify/ask-netlify#54]
## About me

- **My name:** Marino Guerieri
- **I've used Netlify:** a little

## My question

I've recently been introduced to JAM stack and I like it. I'm soon going to be making a website for a client which will be using continous deployment. It will be a very small project (portfolio site basically) and I'm contemplating hosting it on free plan because there's absolutely no reason to go paid.

So, **will there be any downsides to using free plan, such as having reduced bandwidth (loading speed)?** I would be willing to pay some amount of money to be "taken seriously" and receive some guarantees considering uptime etc, but 45$ for Pro plan is way too much for a very basic website. So, what's the catch and is there any? :-)

I've heard that people (including me) are often suspicious of these free static files hosting, because they come from shared hosting (PHP,MySQL) world where everything good costs money and that isn't true here in the static hosting world because it's much simpler so there isn't much cost to providing good service. Is that true?

EDIT:
One additional question: **Do websites hosted on Free plan still use CDN?** I went to look into the matter and several tools informed me that there was no CDN used (based on the fact that all assets were served from marinoguerieri.netlify.com which is the website in question), but when I ran two different "server locator" tools, one informed me that the server was in Germany while another claimed it was in the US. So, I guess it does use CDN. Does the fact that all assets are served from main domain (marinoguerieri.netlify.com) as opposed to something like cdn1.netlify.com/cdn2.netlify.com exclude the use of CDN or does CDN work at DNS level, i.e. routing the traffic to the nearest/fastest server while still displaying the same domain name to the end-user?

I hope it's not too much to answer, but I can't seem to find direct answers to these questions.

I thank you in advance for the time taken to answer these questions. :)

**Comment by j-f1** [comment]
All the information about this should be on [the pricing page](https://www.netlify.com/pricing/). Specifically, free plans use the CDN and have a bandwidth limit of 100GB/month, with a surcharge of $20/100GB/month for overages. If you want the 99.99% uptime guarantee, you’ll have to get the $500+/month enterprise plan. However, if you check out [their status page](https://www.netlifystatus.com/#month), you’ll see that they rarely have downtime.

**Comment by marinoguerieri** [comment]
Thanks for answering.

I will leave the question open in case anybody wants to contribute with their personal experiences or other more specific answers.

**Comment by alexabruck** [comment]
@marinoguerieri Great question. I'm happy that this issue is still open. 
I can see another downside of the free plan:

In Netlify's [**terms of service**](https://www.netlify.com/legal/self-serve-subscription-agreement/) it reads: _"While we always make an effort to communicate clearly and well in advance if we decide a particular website project is not a good fit for our Free Usage Tier, we reserve the right to disable or remove any website project on Netlify’s Free Usage Tier without notice at our sole discretion."_ 
That's pretty scary if you are hosting anything else than fun/experimental projects, but rather a website for a business.

**Comment by alexabruck** [comment]
I asked about this in the Netlify forum and the reply from the community manager was: As long as the site doesn't violate the Acceptable Use Policy they won't take down the site. This applies for all plans probably.

**Comment by Pieparker** [comment]
Hey there! With the release of our revised Pro plan now starting at $19/mo/seat, I'll close this issue.
