### ISSUE TITLE
how to make a DNS For My new Website

### ISSUE THREAD

**Issue by rajanbasktoa** [netlify/ask-netlify#73]
## About me

- **My name:** Curious Colin
- **I've used Netlify:** lots | a little | never yet | what is a Netlify?

## My question in a little more detail

What I really want to ask is...

## Additional comments for Netlify

If you like.

**Comment by Pieparker** [comment]
Hey there! If you still require help, can I ask that you visit [Netlify Community](https://community.netlify.com) and share your question there? You may wish to search and see if this has been asked before!
