### ISSUE TITLE
How does your url.netlify.com link shortener work?

### ISSUE THREAD

**Issue by edjw** [netlify/ask-netlify#75]
## About me

- **My name:** Ed Johnson-Williams
- **I've used Netlify:** lots

## My question in a little more detail

What I really want to ask is...

I want to make a reliable and free/cheap link shortener using my own domain and not using bit.ly etc. Can I do this reliably using netlify with a nice interface behind authentication in a way that’s simple for non-technical users?

## Additional comments for Netlify

If you like.

**Comment by j-f1** [comment]
@kentcdodds has built [`netlify-shortener`](https://github.com/kentcdodds/netlify-shortener), which can be added to via the GitHub UI or a command line tool.

**Comment by edjw** [comment]
Thanks! I’ll take a longer look at this. It seems that the interface at the moment is via the terminal. Is that right?

**Comment by Pieparker** [comment]
Hey there! If you still require help, can I ask that you visit [Netlify Community](https://community.netlify.com) and share your question there? You may wish to search and see if this has been asked before!
