### ISSUE TITLE
At my wit's end with Babel error

### ISSUE THREAD

**Issue by Mykasoda** [netlify/ask-netlify#76]
## About me

- **My name:** Curious Colin
- **I've used Netlify:**a little (but always have errors and give up)

## My question in a little more detail

Hi, I keep getting this error whenever I use continuous deploy on Netlify...
3:36:08 PM: Error: [BABEL] /opt/build/repo/src/index.js: Could not find plugin "proposal-numeric-separator". Ensure there is an entry in ./available-plugins.js for it. (While processing: "/opt/build/repo/node_modules/babel-preset-react-app/index.js$0")
3:36:08 PM:     at Array.map (<anonymous>)
3:36:08 PM:     at Generator.next (<anonymous>)
3:36:08 PM:     at Generator.next (<anonymous>)
3:36:08 PM: error Command failed with exit code 1.

But when I build the files locally then upload it works fine. I've been searching for days and cannot figure out what is even causing the issue, let alone how to fix it, any help would be appreciated immensely.

## Additional comments for Netlify

If you like.

**Comment by Pieparker** [comment]
Hey there! If you still require help, can I ask that you visit [Netlify Community](https://community.netlify.com) and share your question there? You may wish to search and see if this has been asked before!
