### ISSUE TITLE
Need to use a file (json) to write from a netlify site dynamicaly

### ISSUE THREAD

**Issue by NikosAvg** [netlify/ask-netlify#77]
Hello, i'm writing a static site that needs to use a .json file to write some data dynamicaly but haven't found a solution. Netlify doesn't allow writing when the site is deployed is there an other way to do it?

**Comment by Pieparker** [comment]
Hey there! If you still require help, can I ask that you visit [Netlify Community](https://community.netlify.com) and share your question there? You may wish to search and see if this has been asked before!
