### ISSUE TITLE
Access Denied into my Netlify account

### ISSUE THREAD

**Issue by Emmanuel-ctrl** [netlify/ask-netlify#79]
## About me

- **My name:** Emmanuel John
- **I've used Netlify:**  a little and i really enjoyed the experience

## My question in a little more detail

What I really want to ask is...please i need this issue resolved from your back-end i have been denied access into my netfliy account after several attempt to deploy a repo and getting failed.

## Additional comments for Netlify yeah i love netlify hope to do more business with you guys in future.

If you like.

**Comment by manniL** [comment]
I don't think that's the right place to ask. Write to the support instead 😋

**Comment by Pieparker** [comment]
Hey there! As above, if you still need help, can I ask that you visit [our Support page](https://www.netlify.com/support/) and select `LOGIN/SIGNUP`?
