### ISSUE TITLE
Question about being an author of a template

### ISSUE THREAD

**Issue by raniesantos** [netlify/ask-netlify#8]
## About me

- **My name:** Ranie Santos
- **I've used Netlify:** for my personal site and a template based on my site

## My question in a little more detail

Does Netlify have a way of showing me how many times the repo of my Netlify Template has been deployed?

## Anything other comments for Netlify

Netlify is so flexible, convenient, and easy to use. I'm glad I'm not stuck on Jekyll and GitHub pages anymore.

**Comment by philhawksworth** [comment]
I'm afraid not, @raniesantos.

We do track in our internal analytics when a template is deployed via the [Deploy To Netlify Button](https://www.netlify.com/docs/deploy-button/). But we don't currently have a means to expose that data (or other detailed analytics) to customers.

I've heard several people asking for access to analytics based on our builds/CDN activity. But building that out as a suitably capable analytics product is rather complex and not currently planned as far as I know.

Sorry about that, and thanks for the nice comments!

**Comment by talves** [comment]
@philhawksworth someone could just hit their analytics API and transfer the data they needed to track their own builds. It is easy to capture the stdout of the build and scrape it too.

I show how running different build commands with two sites on one repository in the [SO answer](https://stackoverflow.com/a/54171934/2597114). It just happens to capture the output. It may help someone.

✨ I have to try this one! Would make  a great post.
