### ISSUE TITLE
I host my DNS at Cloudflare where could I found the Netlify IPv6

### ISSUE THREAD

**Issue by JOduMonT** [netlify/ask-netlify#81]
## About me

- **My name:** Curious Colin
- **I've used Netlify:** moderately

## My question in a little more detail

https://github.com/netlify/ask-netlify/issues/2
I host my DNS at Cloudflare
where could I found the Netlify IPv6

**Comment by Pieparker** [comment]
We currently do not have an A record for IPv6. If you'd like us to consider this, please ask over at [Netlify Community](https://community.netlify.com). You may wish to search and see if this has been asked before!
