### ISSUE TITLE
Make Netlify show up in GitHub repo deployment environment?

### ISSUE THREAD

**Issue by TimothyGu** [netlify/ask-netlify#82]
## About me

- **My name:** Timothy
- **I've used Netlify:** a little

## My question in a little more detail

We've recently migrated from GitHub Pages to Netlify for our website here: https://github.com/uclaacm/hoth.uclaacm.com. However, when you click on "[environments](https://github.com/uclaacm/hoth.uclaacm.com/deployments)" on that page, only GitHub Pages is shown – even though we no longer use GH Pages.

What would be great if we could have the Netlify deployment log integrated with that interface. The API is available [here](https://developer.github.com/v3/repos/deployments/). It appears that Netlify should also be part of the [GitHub Marketplace](https://github.com/marketplace).

**Comment by Pieparker** [comment]
Hey there! If you'd like us to consider this as a feature, can I ask that you visit [Netlify Community](https://community.netlify.com) and share it there?
