### ISSUE TITLE
How to add pictures to my masonry

### ISSUE THREAD

**Issue by radkoscheper** [netlify/ask-netlify#84]
## About me

- **My name:** Radko
- **I've used Netlify:** lots 

## My question in a little more detail

What I really want to ask is...

On my website I use a masonry layout for my pictures (paintings).
How can I use the Netlify CMS to add pictures and text to this masonry?

www.alyona.be

## Additional comments for Netlify

If you like.

**Comment by Pieparker** [comment]
Hey there! If you still need help, can I ask that you visit [Netlify Community](https://community.netlify.com) and share your question there?
