### ISSUE TITLE
Recommended way to set .env

### ISSUE THREAD

**Issue by NathanHeffley** [netlify/ask-netlify#9]
## About me

- **My name:** Nathan Heffley
- **I've used Netlify:** lots

## My question in a little more detail

I have a Vue CLI based project which uses some .env files to set some values to be used in the build process. Since it's a frontend project ([project for reference](https://github.com/NathanHeffley/pointer-frontend)) the key isn't particularly sensitive amd I've just committed the files, but it makes it more difficult for users who want to change the setting for local testing with their own keys.

I haven't been able to find any good recommendations or examples of how to handle setting variables in a way that's also friendly to local development or deploying to non-Netlify systems.

Thanks in advance for any suggestions!

**Comment by philhawksworth** [comment]
https://www.npmjs.com/package/dotenv is your friend.
(In conjunction with environment variables as supported by Netlify and most comparable platforms)
